name: "keroguic-db"

services:
  db:
    image: postgres:15
    container_name: keroguic
    restart: unless-stopped
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keroguic
    ports:
      - 8001:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
