name: "keroguic-db"

services:
  db:
    image: postgres:15
    container_name: keroguic
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 8001:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
